/********************************************************************************
** Form generated from reading UI file 'config.ui'
**
** Created by: Qt User Interface Compiler version 5.6.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_CONFIG_H
#define UI_CONFIG_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Config
{
public:
    QTabWidget *tabWidget;
    QWidget *tab;
    QTableWidget *tableWidget;
    QTableWidget *tableWidget_2;
    QLabel *label_2;
    QLabel *label_3;
    QPushButton *pushButton_4;
    QPushButton *pushButton_6;
    QPushButton *pushButton_5;
    QTabWidget *tabWidget_2;
    QWidget *tab_5;
    QLabel *label_8;
    QLabel *label_9;
    QLineEdit *lineEdit;
    QLineEdit *lineEdit_2;
    QGroupBox *groupBox;
    QLineEdit *lineEdit_7;
    QLineEdit *lineEdit_5;
    QLabel *label_14;
    QLabel *label_13;
    QGroupBox *groupBox_2;
    QLineEdit *lineEdit_8;
    QLabel *label_15;
    QLabel *label_16;
    QLineEdit *lineEdit_6;
    QWidget *tab_6;
    QLabel *label_10;
    QLabel *label_11;
    QLineEdit *lineEdit_3;
    QLineEdit *lineEdit_4;
    QLineEdit *lineEdit_11;
    QLabel *label_12;
    QLabel *label_19;
    QLineEdit *lineEdit_12;
    QLabel *label_20;
    QLineEdit *lineEdit_13;
    QLineEdit *lineEdit_14;
    QLabel *label_21;
    QWidget *tab_2;
    QPushButton *pushButton_8;
    QPushButton *pushButton_agregar_aduanero;
    QPushButton *pushButton_10;
    QLabel *label_27;
    QListWidget *listWidget;
    QListWidget *listWidget_3;
    QListWidget *listWidget_4;
    QListWidget *listWidget_5;
    QListWidget *listWidget_6;
    QListWidget *listWidget_7;
    QLabel *label_54;
    QLabel *label_55;
    QLabel *label_56;
    QListWidget *listWidget_8;
    QListWidget *listWidget_9;
    QListWidget *listWidget_12;
    QLabel *label_68;
    QLabel *label_69;
    QTabWidget *tabWidget_3;
    QWidget *tab_7;
    QLabel *label_17;
    QLabel *label_18;
    QLineEdit *lineEdit_9;
    QLineEdit *lineEdit_10;
    QLabel *label_22;
    QLineEdit *lineEdit_41;
    QLabel *label_26;
    QLineEdit *lineEdit_42;
    QLineEdit *lineEdit_43;
    QLabel *label_70;
    QLineEdit *lineEdit_44;
    QLabel *label_71;
    QLineEdit *lineEdit_45;
    QLabel *label_72;
    QWidget *tab_8;
    QLabel *label_23;
    QLabel *label_73;
    QLineEdit *lineEdit_;
    QLineEdit *lineEdit_46;
    QLabel *label_24;
    QLabel *label_25;
    QLineEdit *lineEdit_47;
    QLineEdit *lineEdit_16;
    QLineEdit *lineEdit_48;
    QLabel *label_74;
    QLabel *label_75;
    QLineEdit *lineEdit_49;
    QLabel *label_76;
    QLineEdit *lineEdit_50;
    QLabel *label_77;
    QLineEdit *lineEdit_51;
    QLabel *label_78;
    QLineEdit *lineEdit_52;
    QWidget *tab_19;
    QLabel *label_79;
    QLineEdit *lineEdit_aduanero_comision;
    QLabel *label_80;
    QLineEdit *lineEdit_aduanero_gastos_admon;
    QLabel *label_81;
    QLineEdit *lineEdit_aduanero_dvas;
    QLineEdit *lineEdit_aduanero_duas;
    QLabel *label_82;
    QLabel *label_83;
    QLineEdit *lineEdit_aduanero_almacenamiento;
    QLineEdit *lineEdit_aduanero_multas;
    QLabel *label_84;
    QLineEdit *lineEdit_aduanero_dai;
    QLabel *label_85;
    QLabel *label_86;
    QLineEdit *lineEdit_aduanero_std;
    QLineEdit *lineEdit_aduanero_inspeccion;
    QLabel *label_87;
    QWidget *tab_20;
    QLineEdit *lineEdit_62;
    QLineEdit *lineEdit_63;
    QLabel *label_88;
    QLabel *label_89;
    QLabel *label_90;
    QLabel *label_91;
    QLineEdit *lineEdit_64;
    QLineEdit *lineEdit_65;
    QLineEdit *lineEdit_66;
    QLineEdit *lineEdit_67;
    QLabel *label_92;
    QLabel *label_93;
    QLabel *label_94;
    QLabel *label_95;
    QLabel *label_28;
    QComboBox *comboBox_aduanero_proveedor;
    QWidget *tab_3;
    QLabel *label_57;
    QListWidget *listWidget_10;
    QListWidget *listWidget_11;
    QPushButton *pushButton_17;
    QPushButton *pushButton_18;
    QPushButton *pushButton_19;
    QComboBox *comboBox_5;
    QLabel *label_58;
    QGroupBox *groupBox_13;
    QTabWidget *tabWidget_4;
    QWidget *tab_17;
    QLabel *label_59;
    QLabel *label_60;
    QLineEdit *lineEdit_33;
    QLineEdit *lineEdit_34;
    QGroupBox *groupBox_14;
    QLineEdit *lineEdit_35;
    QLineEdit *lineEdit_36;
    QLabel *label_61;
    QLabel *label_62;
    QGroupBox *groupBox_15;
    QLineEdit *lineEdit_37;
    QLabel *label_63;
    QLabel *label_64;
    QLineEdit *lineEdit_38;
    QWidget *tab_18;
    QLabel *label_65;
    QLabel *label_66;
    QTextEdit *textEdit_5;
    QLabel *label_67;
    QLineEdit *lineEdit_39;
    QLineEdit *lineEdit_40;
    QWidget *tab_4;
    QLabel *label_6;
    QLabel *logo;
    QLabel *label_5;
    QLabel *label_4;
    QLabel *label;
    QPushButton *pushButton_7;
    QPushButton *pushButton_cerrar;

    void setupUi(QWidget *Config)
    {
        if (Config->objectName().isEmpty())
            Config->setObjectName(QStringLiteral("Config"));
        Config->resize(1500, 700);
        tabWidget = new QTabWidget(Config);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(10, 60, 1471, 551));
        QFont font;
        font.setPointSize(12);
        font.setBold(true);
        font.setWeight(75);
        tabWidget->setFont(font);
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        tableWidget = new QTableWidget(tab);
        if (tableWidget->columnCount() < 6)
            tableWidget->setColumnCount(6);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(2, __qtablewidgetitem2);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(3, __qtablewidgetitem3);
        QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(4, __qtablewidgetitem4);
        QTableWidgetItem *__qtablewidgetitem5 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(5, __qtablewidgetitem5);
        tableWidget->setObjectName(QStringLiteral("tableWidget"));
        tableWidget->setGeometry(QRect(10, 60, 641, 181));
        tableWidget_2 = new QTableWidget(tab);
        if (tableWidget_2->columnCount() < 6)
            tableWidget_2->setColumnCount(6);
        QTableWidgetItem *__qtablewidgetitem6 = new QTableWidgetItem();
        tableWidget_2->setHorizontalHeaderItem(0, __qtablewidgetitem6);
        QTableWidgetItem *__qtablewidgetitem7 = new QTableWidgetItem();
        tableWidget_2->setHorizontalHeaderItem(1, __qtablewidgetitem7);
        QTableWidgetItem *__qtablewidgetitem8 = new QTableWidgetItem();
        tableWidget_2->setHorizontalHeaderItem(2, __qtablewidgetitem8);
        QTableWidgetItem *__qtablewidgetitem9 = new QTableWidgetItem();
        tableWidget_2->setHorizontalHeaderItem(3, __qtablewidgetitem9);
        QTableWidgetItem *__qtablewidgetitem10 = new QTableWidgetItem();
        tableWidget_2->setHorizontalHeaderItem(4, __qtablewidgetitem10);
        QTableWidgetItem *__qtablewidgetitem11 = new QTableWidgetItem();
        tableWidget_2->setHorizontalHeaderItem(5, __qtablewidgetitem11);
        tableWidget_2->setObjectName(QStringLiteral("tableWidget_2"));
        tableWidget_2->setGeometry(QRect(10, 281, 641, 161));
        label_2 = new QLabel(tab);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(10, 30, 611, 21));
        label_2->setFont(font);
        label_2->setAlignment(Qt::AlignCenter);
        label_3 = new QLabel(tab);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(10, 250, 611, 21));
        label_3->setFont(font);
        label_3->setAlignment(Qt::AlignCenter);
        pushButton_4 = new QPushButton(tab);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(1140, 150, 121, 71));
        QFont font1;
        font1.setPointSize(11);
        font1.setBold(true);
        font1.setWeight(75);
        pushButton_4->setFont(font1);
        pushButton_6 = new QPushButton(tab);
        pushButton_6->setObjectName(QStringLiteral("pushButton_6"));
        pushButton_6->setGeometry(QRect(1140, 330, 121, 71));
        pushButton_6->setFont(font1);
        pushButton_5 = new QPushButton(tab);
        pushButton_5->setObjectName(QStringLiteral("pushButton_5"));
        pushButton_5->setGeometry(QRect(1140, 240, 121, 71));
        pushButton_5->setFont(font1);
        tabWidget_2 = new QTabWidget(tab);
        tabWidget_2->setObjectName(QStringLiteral("tabWidget_2"));
        tabWidget_2->setGeometry(QRect(670, 10, 461, 451));
        QFont font2;
        font2.setPointSize(9);
        font2.setBold(true);
        font2.setWeight(75);
        tabWidget_2->setFont(font2);
        tab_5 = new QWidget();
        tab_5->setObjectName(QStringLiteral("tab_5"));
        label_8 = new QLabel(tab_5);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(290, 10, 71, 21));
        label_8->setFont(font2);
        label_8->setAlignment(Qt::AlignCenter);
        label_9 = new QLabel(tab_5);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(10, 10, 91, 21));
        label_9->setFont(font2);
        label_9->setAlignment(Qt::AlignCenter);
        lineEdit = new QLineEdit(tab_5);
        lineEdit->setObjectName(QStringLiteral("lineEdit"));
        lineEdit->setGeometry(QRect(10, 40, 191, 31));
        lineEdit_2 = new QLineEdit(tab_5);
        lineEdit_2->setObjectName(QStringLiteral("lineEdit_2"));
        lineEdit_2->setGeometry(QRect(230, 40, 201, 31));
        groupBox = new QGroupBox(tab_5);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(10, 110, 431, 131));
        lineEdit_7 = new QLineEdit(groupBox);
        lineEdit_7->setObjectName(QStringLiteral("lineEdit_7"));
        lineEdit_7->setGeometry(QRect(220, 60, 201, 31));
        lineEdit_5 = new QLineEdit(groupBox);
        lineEdit_5->setObjectName(QStringLiteral("lineEdit_5"));
        lineEdit_5->setGeometry(QRect(10, 60, 201, 31));
        label_14 = new QLabel(groupBox);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(230, 30, 181, 21));
        label_14->setFont(font2);
        label_14->setAlignment(Qt::AlignCenter);
        label_13 = new QLabel(groupBox);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(10, 30, 201, 21));
        label_13->setFont(font2);
        label_13->setAlignment(Qt::AlignCenter);
        groupBox_2 = new QGroupBox(tab_5);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setGeometry(QRect(10, 270, 431, 141));
        lineEdit_8 = new QLineEdit(groupBox_2);
        lineEdit_8->setObjectName(QStringLiteral("lineEdit_8"));
        lineEdit_8->setGeometry(QRect(220, 70, 201, 31));
        label_15 = new QLabel(groupBox_2);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(10, 50, 201, 21));
        label_15->setFont(font2);
        label_15->setAlignment(Qt::AlignCenter);
        label_16 = new QLabel(groupBox_2);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(220, 50, 201, 21));
        label_16->setFont(font2);
        label_16->setAlignment(Qt::AlignCenter);
        lineEdit_6 = new QLineEdit(groupBox_2);
        lineEdit_6->setObjectName(QStringLiteral("lineEdit_6"));
        lineEdit_6->setGeometry(QRect(10, 70, 201, 31));
        tabWidget_2->addTab(tab_5, QString());
        tab_6 = new QWidget();
        tab_6->setObjectName(QStringLiteral("tab_6"));
        label_10 = new QLabel(tab_6);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(30, 40, 181, 31));
        label_10->setFont(font2);
        label_10->setAlignment(Qt::AlignCenter);
        label_11 = new QLabel(tab_6);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(30, 90, 181, 31));
        label_11->setFont(font2);
        label_11->setAlignment(Qt::AlignCenter);
        lineEdit_3 = new QLineEdit(tab_6);
        lineEdit_3->setObjectName(QStringLiteral("lineEdit_3"));
        lineEdit_3->setGeometry(QRect(240, 50, 181, 31));
        QFont font3;
        font3.setPointSize(8);
        lineEdit_3->setFont(font3);
        lineEdit_4 = new QLineEdit(tab_6);
        lineEdit_4->setObjectName(QStringLiteral("lineEdit_4"));
        lineEdit_4->setGeometry(QRect(240, 100, 181, 31));
        lineEdit_4->setFont(font3);
        lineEdit_11 = new QLineEdit(tab_6);
        lineEdit_11->setObjectName(QStringLiteral("lineEdit_11"));
        lineEdit_11->setGeometry(QRect(240, 150, 181, 31));
        lineEdit_11->setFont(font3);
        label_12 = new QLabel(tab_6);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(30, 150, 181, 31));
        label_12->setFont(font2);
        label_12->setAlignment(Qt::AlignCenter);
        label_19 = new QLabel(tab_6);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(30, 200, 181, 31));
        label_19->setFont(font2);
        label_19->setAlignment(Qt::AlignCenter);
        lineEdit_12 = new QLineEdit(tab_6);
        lineEdit_12->setObjectName(QStringLiteral("lineEdit_12"));
        lineEdit_12->setGeometry(QRect(240, 200, 181, 31));
        lineEdit_12->setFont(font3);
        label_20 = new QLabel(tab_6);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(30, 240, 181, 31));
        label_20->setFont(font2);
        label_20->setAlignment(Qt::AlignCenter);
        lineEdit_13 = new QLineEdit(tab_6);
        lineEdit_13->setObjectName(QStringLiteral("lineEdit_13"));
        lineEdit_13->setGeometry(QRect(240, 250, 181, 31));
        lineEdit_13->setFont(font3);
        lineEdit_14 = new QLineEdit(tab_6);
        lineEdit_14->setObjectName(QStringLiteral("lineEdit_14"));
        lineEdit_14->setGeometry(QRect(240, 300, 181, 31));
        lineEdit_14->setFont(font3);
        label_21 = new QLabel(tab_6);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(20, 300, 181, 31));
        label_21->setFont(font2);
        label_21->setAlignment(Qt::AlignCenter);
        tabWidget_2->addTab(tab_6, QString());
        tabWidget->addTab(tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        pushButton_8 = new QPushButton(tab_2);
        pushButton_8->setObjectName(QStringLiteral("pushButton_8"));
        pushButton_8->setGeometry(QRect(1320, 290, 121, 71));
        pushButton_8->setFont(font1);
        pushButton_agregar_aduanero = new QPushButton(tab_2);
        pushButton_agregar_aduanero->setObjectName(QStringLiteral("pushButton_agregar_aduanero"));
        pushButton_agregar_aduanero->setGeometry(QRect(1320, 110, 121, 71));
        pushButton_agregar_aduanero->setFont(font1);
        pushButton_10 = new QPushButton(tab_2);
        pushButton_10->setObjectName(QStringLiteral("pushButton_10"));
        pushButton_10->setGeometry(QRect(1320, 200, 121, 71));
        pushButton_10->setFont(font1);
        label_27 = new QLabel(tab_2);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(20, 40, 291, 21));
        label_27->setFont(font2);
        label_27->setAlignment(Qt::AlignCenter);
        listWidget = new QListWidget(tab_2);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        listWidget->setObjectName(QStringLiteral("listWidget"));
        listWidget->setGeometry(QRect(20, 80, 151, 161));
        listWidget_3 = new QListWidget(tab_2);
        listWidget_3->setObjectName(QStringLiteral("listWidget_3"));
        listWidget_3->setGeometry(QRect(170, 80, 141, 161));
        listWidget_4 = new QListWidget(tab_2);
        new QListWidgetItem(listWidget_4);
        new QListWidgetItem(listWidget_4);
        new QListWidgetItem(listWidget_4);
        new QListWidgetItem(listWidget_4);
        new QListWidgetItem(listWidget_4);
        new QListWidgetItem(listWidget_4);
        new QListWidgetItem(listWidget_4);
        new QListWidgetItem(listWidget_4);
        new QListWidgetItem(listWidget_4);
        listWidget_4->setObjectName(QStringLiteral("listWidget_4"));
        listWidget_4->setGeometry(QRect(340, 80, 171, 161));
        listWidget_5 = new QListWidget(tab_2);
        listWidget_5->setObjectName(QStringLiteral("listWidget_5"));
        listWidget_5->setGeometry(QRect(510, 80, 181, 161));
        listWidget_6 = new QListWidget(tab_2);
        new QListWidgetItem(listWidget_6);
        new QListWidgetItem(listWidget_6);
        new QListWidgetItem(listWidget_6);
        new QListWidgetItem(listWidget_6);
        new QListWidgetItem(listWidget_6);
        new QListWidgetItem(listWidget_6);
        new QListWidgetItem(listWidget_6);
        new QListWidgetItem(listWidget_6);
        new QListWidgetItem(listWidget_6);
        listWidget_6->setObjectName(QStringLiteral("listWidget_6"));
        listWidget_6->setGeometry(QRect(20, 290, 171, 171));
        listWidget_7 = new QListWidget(tab_2);
        listWidget_7->setObjectName(QStringLiteral("listWidget_7"));
        listWidget_7->setGeometry(QRect(190, 290, 121, 171));
        label_54 = new QLabel(tab_2);
        label_54->setObjectName(QStringLiteral("label_54"));
        label_54->setGeometry(QRect(350, 40, 131, 21));
        label_54->setFont(font2);
        label_54->setAlignment(Qt::AlignCenter);
        label_55 = new QLabel(tab_2);
        label_55->setObjectName(QStringLiteral("label_55"));
        label_55->setGeometry(QRect(20, 260, 241, 21));
        label_55->setFont(font2);
        label_55->setAlignment(Qt::AlignCenter);
        label_56 = new QLabel(tab_2);
        label_56->setObjectName(QStringLiteral("label_56"));
        label_56->setGeometry(QRect(360, 260, 331, 21));
        label_56->setFont(font2);
        label_56->setAlignment(Qt::AlignCenter);
        listWidget_8 = new QListWidget(tab_2);
        listWidget_8->setObjectName(QStringLiteral("listWidget_8"));
        listWidget_8->setGeometry(QRect(470, 310, 111, 151));
        listWidget_9 = new QListWidget(tab_2);
        new QListWidgetItem(listWidget_9);
        new QListWidgetItem(listWidget_9);
        new QListWidgetItem(listWidget_9);
        listWidget_9->setObjectName(QStringLiteral("listWidget_9"));
        listWidget_9->setGeometry(QRect(350, 310, 121, 151));
        listWidget_12 = new QListWidget(tab_2);
        listWidget_12->setObjectName(QStringLiteral("listWidget_12"));
        listWidget_12->setGeometry(QRect(580, 310, 111, 151));
        label_68 = new QLabel(tab_2);
        label_68->setObjectName(QStringLiteral("label_68"));
        label_68->setGeometry(QRect(470, 290, 111, 21));
        label_68->setFont(font2);
        label_68->setAlignment(Qt::AlignCenter);
        label_69 = new QLabel(tab_2);
        label_69->setObjectName(QStringLiteral("label_69"));
        label_69->setGeometry(QRect(580, 290, 111, 21));
        label_69->setFont(font2);
        label_69->setAlignment(Qt::AlignCenter);
        tabWidget_3 = new QTabWidget(tab_2);
        tabWidget_3->setObjectName(QStringLiteral("tabWidget_3"));
        tabWidget_3->setGeometry(QRect(780, 60, 501, 451));
        tabWidget_3->setFont(font2);
        tab_7 = new QWidget();
        tab_7->setObjectName(QStringLiteral("tab_7"));
        label_17 = new QLabel(tab_7);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(40, 110, 131, 21));
        label_17->setFont(font2);
        label_17->setAlignment(Qt::AlignCenter);
        label_18 = new QLabel(tab_7);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(30, 50, 141, 21));
        label_18->setFont(font2);
        label_18->setAlignment(Qt::AlignCenter);
        lineEdit_9 = new QLineEdit(tab_7);
        lineEdit_9->setObjectName(QStringLiteral("lineEdit_9"));
        lineEdit_9->setGeometry(QRect(230, 40, 231, 31));
        lineEdit_10 = new QLineEdit(tab_7);
        lineEdit_10->setObjectName(QStringLiteral("lineEdit_10"));
        lineEdit_10->setGeometry(QRect(230, 100, 241, 31));
        label_22 = new QLabel(tab_7);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(40, 160, 131, 21));
        label_22->setFont(font2);
        label_22->setAlignment(Qt::AlignCenter);
        lineEdit_41 = new QLineEdit(tab_7);
        lineEdit_41->setObjectName(QStringLiteral("lineEdit_41"));
        lineEdit_41->setGeometry(QRect(230, 150, 241, 31));
        label_26 = new QLabel(tab_7);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(20, 200, 181, 21));
        label_26->setFont(font2);
        label_26->setAlignment(Qt::AlignCenter);
        lineEdit_42 = new QLineEdit(tab_7);
        lineEdit_42->setObjectName(QStringLiteral("lineEdit_42"));
        lineEdit_42->setGeometry(QRect(230, 190, 241, 31));
        lineEdit_43 = new QLineEdit(tab_7);
        lineEdit_43->setObjectName(QStringLiteral("lineEdit_43"));
        lineEdit_43->setGeometry(QRect(230, 240, 241, 31));
        label_70 = new QLabel(tab_7);
        label_70->setObjectName(QStringLiteral("label_70"));
        label_70->setGeometry(QRect(30, 240, 151, 21));
        label_70->setFont(font2);
        label_70->setAlignment(Qt::AlignCenter);
        lineEdit_44 = new QLineEdit(tab_7);
        lineEdit_44->setObjectName(QStringLiteral("lineEdit_44"));
        lineEdit_44->setGeometry(QRect(230, 290, 241, 31));
        label_71 = new QLabel(tab_7);
        label_71->setObjectName(QStringLiteral("label_71"));
        label_71->setGeometry(QRect(30, 290, 151, 21));
        label_71->setFont(font2);
        label_71->setAlignment(Qt::AlignCenter);
        lineEdit_45 = new QLineEdit(tab_7);
        lineEdit_45->setObjectName(QStringLiteral("lineEdit_45"));
        lineEdit_45->setGeometry(QRect(230, 340, 241, 31));
        label_72 = new QLabel(tab_7);
        label_72->setObjectName(QStringLiteral("label_72"));
        label_72->setGeometry(QRect(30, 340, 151, 21));
        label_72->setFont(font2);
        label_72->setAlignment(Qt::AlignCenter);
        tabWidget_3->addTab(tab_7, QString());
        tab_8 = new QWidget();
        tab_8->setObjectName(QStringLiteral("tab_8"));
        label_23 = new QLabel(tab_8);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(40, 70, 131, 21));
        label_23->setFont(font2);
        label_23->setAlignment(Qt::AlignCenter);
        label_73 = new QLabel(tab_8);
        label_73->setObjectName(QStringLiteral("label_73"));
        label_73->setGeometry(QRect(30, 210, 151, 21));
        label_73->setFont(font2);
        label_73->setAlignment(Qt::AlignCenter);
        lineEdit_ = new QLineEdit(tab_8);
        lineEdit_->setObjectName(QStringLiteral("lineEdit_"));
        lineEdit_->setGeometry(QRect(190, 30, 241, 31));
        lineEdit_46 = new QLineEdit(tab_8);
        lineEdit_46->setObjectName(QStringLiteral("lineEdit_46"));
        lineEdit_46->setGeometry(QRect(190, 110, 241, 31));
        label_24 = new QLabel(tab_8);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(30, 30, 141, 21));
        label_24->setFont(font2);
        label_24->setAlignment(Qt::AlignCenter);
        label_25 = new QLabel(tab_8);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(40, 110, 131, 21));
        label_25->setFont(font2);
        label_25->setAlignment(Qt::AlignCenter);
        lineEdit_47 = new QLineEdit(tab_8);
        lineEdit_47->setObjectName(QStringLiteral("lineEdit_47"));
        lineEdit_47->setGeometry(QRect(190, 150, 241, 31));
        lineEdit_16 = new QLineEdit(tab_8);
        lineEdit_16->setObjectName(QStringLiteral("lineEdit_16"));
        lineEdit_16->setGeometry(QRect(190, 70, 241, 31));
        lineEdit_48 = new QLineEdit(tab_8);
        lineEdit_48->setObjectName(QStringLiteral("lineEdit_48"));
        lineEdit_48->setGeometry(QRect(190, 200, 241, 31));
        label_74 = new QLabel(tab_8);
        label_74->setObjectName(QStringLiteral("label_74"));
        label_74->setGeometry(QRect(30, 160, 141, 21));
        label_74->setFont(font2);
        label_74->setAlignment(Qt::AlignCenter);
        label_75 = new QLabel(tab_8);
        label_75->setObjectName(QStringLiteral("label_75"));
        label_75->setGeometry(QRect(30, 250, 151, 21));
        label_75->setFont(font2);
        label_75->setAlignment(Qt::AlignCenter);
        lineEdit_49 = new QLineEdit(tab_8);
        lineEdit_49->setObjectName(QStringLiteral("lineEdit_49"));
        lineEdit_49->setGeometry(QRect(190, 250, 241, 31));
        label_76 = new QLabel(tab_8);
        label_76->setObjectName(QStringLiteral("label_76"));
        label_76->setGeometry(QRect(30, 310, 151, 21));
        label_76->setFont(font2);
        label_76->setAlignment(Qt::AlignCenter);
        lineEdit_50 = new QLineEdit(tab_8);
        lineEdit_50->setObjectName(QStringLiteral("lineEdit_50"));
        lineEdit_50->setGeometry(QRect(190, 300, 241, 31));
        label_77 = new QLabel(tab_8);
        label_77->setObjectName(QStringLiteral("label_77"));
        label_77->setGeometry(QRect(30, 350, 151, 21));
        label_77->setFont(font2);
        label_77->setAlignment(Qt::AlignCenter);
        lineEdit_51 = new QLineEdit(tab_8);
        lineEdit_51->setObjectName(QStringLiteral("lineEdit_51"));
        lineEdit_51->setGeometry(QRect(190, 340, 241, 31));
        label_78 = new QLabel(tab_8);
        label_78->setObjectName(QStringLiteral("label_78"));
        label_78->setGeometry(QRect(30, 390, 151, 21));
        label_78->setFont(font2);
        label_78->setAlignment(Qt::AlignCenter);
        lineEdit_52 = new QLineEdit(tab_8);
        lineEdit_52->setObjectName(QStringLiteral("lineEdit_52"));
        lineEdit_52->setGeometry(QRect(190, 380, 241, 31));
        tabWidget_3->addTab(tab_8, QString());
        tab_19 = new QWidget();
        tab_19->setObjectName(QStringLiteral("tab_19"));
        label_79 = new QLabel(tab_19);
        label_79->setObjectName(QStringLiteral("label_79"));
        label_79->setGeometry(QRect(40, 100, 131, 21));
        label_79->setFont(font2);
        label_79->setAlignment(Qt::AlignCenter);
        lineEdit_aduanero_comision = new QLineEdit(tab_19);
        lineEdit_aduanero_comision->setObjectName(QStringLiteral("lineEdit_aduanero_comision"));
        lineEdit_aduanero_comision->setGeometry(QRect(190, 60, 241, 31));
        label_80 = new QLabel(tab_19);
        label_80->setObjectName(QStringLiteral("label_80"));
        label_80->setGeometry(QRect(40, 20, 131, 21));
        label_80->setFont(font2);
        label_80->setAlignment(Qt::AlignCenter);
        lineEdit_aduanero_gastos_admon = new QLineEdit(tab_19);
        lineEdit_aduanero_gastos_admon->setObjectName(QStringLiteral("lineEdit_aduanero_gastos_admon"));
        lineEdit_aduanero_gastos_admon->setGeometry(QRect(190, 20, 241, 31));
        label_81 = new QLabel(tab_19);
        label_81->setObjectName(QStringLiteral("label_81"));
        label_81->setGeometry(QRect(40, 60, 131, 21));
        label_81->setFont(font2);
        label_81->setAlignment(Qt::AlignCenter);
        lineEdit_aduanero_dvas = new QLineEdit(tab_19);
        lineEdit_aduanero_dvas->setObjectName(QStringLiteral("lineEdit_aduanero_dvas"));
        lineEdit_aduanero_dvas->setGeometry(QRect(190, 100, 241, 31));
        lineEdit_aduanero_duas = new QLineEdit(tab_19);
        lineEdit_aduanero_duas->setObjectName(QStringLiteral("lineEdit_aduanero_duas"));
        lineEdit_aduanero_duas->setGeometry(QRect(190, 140, 241, 31));
        label_82 = new QLabel(tab_19);
        label_82->setObjectName(QStringLiteral("label_82"));
        label_82->setGeometry(QRect(40, 140, 131, 21));
        label_82->setFont(font2);
        label_82->setAlignment(Qt::AlignCenter);
        label_83 = new QLabel(tab_19);
        label_83->setObjectName(QStringLiteral("label_83"));
        label_83->setGeometry(QRect(40, 180, 131, 21));
        label_83->setFont(font2);
        label_83->setAlignment(Qt::AlignCenter);
        lineEdit_aduanero_almacenamiento = new QLineEdit(tab_19);
        lineEdit_aduanero_almacenamiento->setObjectName(QStringLiteral("lineEdit_aduanero_almacenamiento"));
        lineEdit_aduanero_almacenamiento->setGeometry(QRect(190, 180, 241, 31));
        lineEdit_aduanero_multas = new QLineEdit(tab_19);
        lineEdit_aduanero_multas->setObjectName(QStringLiteral("lineEdit_aduanero_multas"));
        lineEdit_aduanero_multas->setGeometry(QRect(190, 220, 241, 31));
        label_84 = new QLabel(tab_19);
        label_84->setObjectName(QStringLiteral("label_84"));
        label_84->setGeometry(QRect(40, 220, 131, 21));
        label_84->setFont(font2);
        label_84->setAlignment(Qt::AlignCenter);
        lineEdit_aduanero_dai = new QLineEdit(tab_19);
        lineEdit_aduanero_dai->setObjectName(QStringLiteral("lineEdit_aduanero_dai"));
        lineEdit_aduanero_dai->setGeometry(QRect(190, 260, 241, 31));
        label_85 = new QLabel(tab_19);
        label_85->setObjectName(QStringLiteral("label_85"));
        label_85->setGeometry(QRect(40, 260, 131, 21));
        label_85->setFont(font2);
        label_85->setAlignment(Qt::AlignCenter);
        label_86 = new QLabel(tab_19);
        label_86->setObjectName(QStringLiteral("label_86"));
        label_86->setGeometry(QRect(40, 300, 131, 21));
        label_86->setFont(font2);
        label_86->setAlignment(Qt::AlignCenter);
        lineEdit_aduanero_std = new QLineEdit(tab_19);
        lineEdit_aduanero_std->setObjectName(QStringLiteral("lineEdit_aduanero_std"));
        lineEdit_aduanero_std->setGeometry(QRect(190, 300, 241, 31));
        lineEdit_aduanero_inspeccion = new QLineEdit(tab_19);
        lineEdit_aduanero_inspeccion->setObjectName(QStringLiteral("lineEdit_aduanero_inspeccion"));
        lineEdit_aduanero_inspeccion->setGeometry(QRect(190, 340, 241, 31));
        label_87 = new QLabel(tab_19);
        label_87->setObjectName(QStringLiteral("label_87"));
        label_87->setGeometry(QRect(40, 340, 131, 21));
        label_87->setFont(font2);
        label_87->setAlignment(Qt::AlignCenter);
        tabWidget_3->addTab(tab_19, QString());
        tab_20 = new QWidget();
        tab_20->setObjectName(QStringLiteral("tab_20"));
        lineEdit_62 = new QLineEdit(tab_20);
        lineEdit_62->setObjectName(QStringLiteral("lineEdit_62"));
        lineEdit_62->setGeometry(QRect(190, 160, 241, 31));
        lineEdit_63 = new QLineEdit(tab_20);
        lineEdit_63->setObjectName(QStringLiteral("lineEdit_63"));
        lineEdit_63->setGeometry(QRect(190, 290, 241, 31));
        label_88 = new QLabel(tab_20);
        label_88->setObjectName(QStringLiteral("label_88"));
        label_88->setGeometry(QRect(40, 290, 131, 21));
        label_88->setFont(font2);
        label_88->setAlignment(Qt::AlignCenter);
        label_89 = new QLabel(tab_20);
        label_89->setObjectName(QStringLiteral("label_89"));
        label_89->setGeometry(QRect(40, 120, 131, 21));
        label_89->setFont(font2);
        label_89->setAlignment(Qt::AlignCenter);
        label_90 = new QLabel(tab_20);
        label_90->setObjectName(QStringLiteral("label_90"));
        label_90->setGeometry(QRect(40, 250, 131, 21));
        label_90->setFont(font2);
        label_90->setAlignment(Qt::AlignCenter);
        label_91 = new QLabel(tab_20);
        label_91->setObjectName(QStringLiteral("label_91"));
        label_91->setGeometry(QRect(40, 80, 131, 21));
        label_91->setFont(font2);
        label_91->setAlignment(Qt::AlignCenter);
        lineEdit_64 = new QLineEdit(tab_20);
        lineEdit_64->setObjectName(QStringLiteral("lineEdit_64"));
        lineEdit_64->setGeometry(QRect(190, 120, 241, 31));
        lineEdit_65 = new QLineEdit(tab_20);
        lineEdit_65->setObjectName(QStringLiteral("lineEdit_65"));
        lineEdit_65->setGeometry(QRect(190, 80, 241, 31));
        lineEdit_66 = new QLineEdit(tab_20);
        lineEdit_66->setObjectName(QStringLiteral("lineEdit_66"));
        lineEdit_66->setGeometry(QRect(190, 250, 241, 31));
        lineEdit_67 = new QLineEdit(tab_20);
        lineEdit_67->setObjectName(QStringLiteral("lineEdit_67"));
        lineEdit_67->setGeometry(QRect(190, 330, 241, 31));
        label_92 = new QLabel(tab_20);
        label_92->setObjectName(QStringLiteral("label_92"));
        label_92->setGeometry(QRect(40, 330, 131, 21));
        label_92->setFont(font2);
        label_92->setAlignment(Qt::AlignCenter);
        label_93 = new QLabel(tab_20);
        label_93->setObjectName(QStringLiteral("label_93"));
        label_93->setGeometry(QRect(40, 160, 131, 21));
        label_93->setFont(font2);
        label_93->setAlignment(Qt::AlignCenter);
        label_94 = new QLabel(tab_20);
        label_94->setObjectName(QStringLiteral("label_94"));
        label_94->setGeometry(QRect(50, 220, 381, 21));
        label_94->setFont(font2);
        label_94->setAlignment(Qt::AlignCenter);
        label_95 = new QLabel(tab_20);
        label_95->setObjectName(QStringLiteral("label_95"));
        label_95->setGeometry(QRect(40, 40, 381, 21));
        label_95->setFont(font2);
        label_95->setAlignment(Qt::AlignCenter);
        tabWidget_3->addTab(tab_20, QString());
        label_28 = new QLabel(tab_2);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(820, 20, 141, 21));
        label_28->setFont(font2);
        label_28->setAlignment(Qt::AlignCenter);
        comboBox_aduanero_proveedor = new QComboBox(tab_2);
        comboBox_aduanero_proveedor->setObjectName(QStringLiteral("comboBox_aduanero_proveedor"));
        comboBox_aduanero_proveedor->setGeometry(QRect(980, 11, 231, 41));
        tabWidget->addTab(tab_2, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QStringLiteral("tab_3"));
        label_57 = new QLabel(tab_3);
        label_57->setObjectName(QStringLiteral("label_57"));
        label_57->setGeometry(QRect(380, 20, 131, 21));
        label_57->setFont(font2);
        label_57->setAlignment(Qt::AlignCenter);
        listWidget_10 = new QListWidget(tab_3);
        listWidget_10->setObjectName(QStringLiteral("listWidget_10"));
        listWidget_10->setGeometry(QRect(440, 50, 121, 171));
        listWidget_11 = new QListWidget(tab_3);
        new QListWidgetItem(listWidget_11);
        new QListWidgetItem(listWidget_11);
        new QListWidgetItem(listWidget_11);
        new QListWidgetItem(listWidget_11);
        new QListWidgetItem(listWidget_11);
        new QListWidgetItem(listWidget_11);
        new QListWidgetItem(listWidget_11);
        new QListWidgetItem(listWidget_11);
        new QListWidgetItem(listWidget_11);
        listWidget_11->setObjectName(QStringLiteral("listWidget_11"));
        listWidget_11->setGeometry(QRect(320, 50, 121, 171));
        pushButton_17 = new QPushButton(tab_3);
        pushButton_17->setObjectName(QStringLiteral("pushButton_17"));
        pushButton_17->setGeometry(QRect(1130, 230, 121, 71));
        pushButton_17->setFont(font1);
        pushButton_18 = new QPushButton(tab_3);
        pushButton_18->setObjectName(QStringLiteral("pushButton_18"));
        pushButton_18->setGeometry(QRect(1130, 320, 121, 71));
        pushButton_18->setFont(font1);
        pushButton_19 = new QPushButton(tab_3);
        pushButton_19->setObjectName(QStringLiteral("pushButton_19"));
        pushButton_19->setGeometry(QRect(1130, 140, 121, 71));
        pushButton_19->setFont(font1);
        comboBox_5 = new QComboBox(tab_3);
        comboBox_5->setObjectName(QStringLiteral("comboBox_5"));
        comboBox_5->setGeometry(QRect(640, 50, 601, 41));
        label_58 = new QLabel(tab_3);
        label_58->setObjectName(QStringLiteral("label_58"));
        label_58->setGeometry(QRect(630, 20, 611, 21));
        label_58->setFont(font);
        label_58->setAlignment(Qt::AlignCenter);
        groupBox_13 = new QGroupBox(tab_3);
        groupBox_13->setObjectName(QStringLiteral("groupBox_13"));
        groupBox_13->setGeometry(QRect(640, 120, 481, 331));
        groupBox_13->setFont(font1);
        tabWidget_4 = new QTabWidget(groupBox_13);
        tabWidget_4->setObjectName(QStringLiteral("tabWidget_4"));
        tabWidget_4->setGeometry(QRect(10, 20, 461, 301));
        tabWidget_4->setFont(font2);
        tab_17 = new QWidget();
        tab_17->setObjectName(QStringLiteral("tab_17"));
        label_59 = new QLabel(tab_17);
        label_59->setObjectName(QStringLiteral("label_59"));
        label_59->setGeometry(QRect(290, 10, 71, 21));
        label_59->setFont(font2);
        label_59->setAlignment(Qt::AlignCenter);
        label_60 = new QLabel(tab_17);
        label_60->setObjectName(QStringLiteral("label_60"));
        label_60->setGeometry(QRect(10, 10, 91, 21));
        label_60->setFont(font2);
        label_60->setAlignment(Qt::AlignCenter);
        lineEdit_33 = new QLineEdit(tab_17);
        lineEdit_33->setObjectName(QStringLiteral("lineEdit_33"));
        lineEdit_33->setGeometry(QRect(10, 40, 191, 31));
        lineEdit_34 = new QLineEdit(tab_17);
        lineEdit_34->setObjectName(QStringLiteral("lineEdit_34"));
        lineEdit_34->setGeometry(QRect(230, 40, 201, 31));
        groupBox_14 = new QGroupBox(tab_17);
        groupBox_14->setObjectName(QStringLiteral("groupBox_14"));
        groupBox_14->setGeometry(QRect(0, 90, 221, 171));
        lineEdit_35 = new QLineEdit(groupBox_14);
        lineEdit_35->setObjectName(QStringLiteral("lineEdit_35"));
        lineEdit_35->setGeometry(QRect(10, 100, 201, 31));
        lineEdit_36 = new QLineEdit(groupBox_14);
        lineEdit_36->setObjectName(QStringLiteral("lineEdit_36"));
        lineEdit_36->setGeometry(QRect(10, 40, 201, 31));
        label_61 = new QLabel(groupBox_14);
        label_61->setObjectName(QStringLiteral("label_61"));
        label_61->setGeometry(QRect(10, 70, 201, 21));
        label_61->setFont(font2);
        label_61->setAlignment(Qt::AlignCenter);
        label_62 = new QLabel(groupBox_14);
        label_62->setObjectName(QStringLiteral("label_62"));
        label_62->setGeometry(QRect(10, 20, 201, 21));
        label_62->setFont(font2);
        label_62->setAlignment(Qt::AlignCenter);
        groupBox_15 = new QGroupBox(tab_17);
        groupBox_15->setObjectName(QStringLiteral("groupBox_15"));
        groupBox_15->setGeometry(QRect(230, 90, 221, 171));
        lineEdit_37 = new QLineEdit(groupBox_15);
        lineEdit_37->setObjectName(QStringLiteral("lineEdit_37"));
        lineEdit_37->setGeometry(QRect(10, 90, 201, 31));
        label_63 = new QLabel(groupBox_15);
        label_63->setObjectName(QStringLiteral("label_63"));
        label_63->setGeometry(QRect(10, 20, 201, 21));
        label_63->setFont(font2);
        label_63->setAlignment(Qt::AlignCenter);
        label_64 = new QLabel(groupBox_15);
        label_64->setObjectName(QStringLiteral("label_64"));
        label_64->setGeometry(QRect(10, 70, 201, 21));
        label_64->setFont(font2);
        label_64->setAlignment(Qt::AlignCenter);
        lineEdit_38 = new QLineEdit(groupBox_15);
        lineEdit_38->setObjectName(QStringLiteral("lineEdit_38"));
        lineEdit_38->setGeometry(QRect(10, 40, 201, 31));
        tabWidget_4->addTab(tab_17, QString());
        tab_18 = new QWidget();
        tab_18->setObjectName(QStringLiteral("tab_18"));
        label_65 = new QLabel(tab_18);
        label_65->setObjectName(QStringLiteral("label_65"));
        label_65->setGeometry(QRect(10, 0, 181, 31));
        label_65->setFont(font2);
        label_65->setAlignment(Qt::AlignCenter);
        label_66 = new QLabel(tab_18);
        label_66->setObjectName(QStringLiteral("label_66"));
        label_66->setGeometry(QRect(200, 0, 111, 31));
        label_66->setFont(font2);
        label_66->setAlignment(Qt::AlignCenter);
        textEdit_5 = new QTextEdit(tab_18);
        textEdit_5->setObjectName(QStringLiteral("textEdit_5"));
        textEdit_5->setGeometry(QRect(10, 80, 301, 101));
        textEdit_5->setFont(font3);
        label_67 = new QLabel(tab_18);
        label_67->setObjectName(QStringLiteral("label_67"));
        label_67->setGeometry(QRect(10, 51, 301, 31));
        label_67->setFont(font2);
        label_67->setAlignment(Qt::AlignCenter);
        lineEdit_39 = new QLineEdit(tab_18);
        lineEdit_39->setObjectName(QStringLiteral("lineEdit_39"));
        lineEdit_39->setGeometry(QRect(10, 30, 181, 20));
        lineEdit_39->setFont(font3);
        lineEdit_40 = new QLineEdit(tab_18);
        lineEdit_40->setObjectName(QStringLiteral("lineEdit_40"));
        lineEdit_40->setGeometry(QRect(200, 30, 111, 20));
        lineEdit_40->setFont(font3);
        tabWidget_4->addTab(tab_18, QString());
        tabWidget->addTab(tab_3, QString());
        tab_4 = new QWidget();
        tab_4->setObjectName(QStringLiteral("tab_4"));
        label_6 = new QLabel(tab_4);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(0, 380, 1241, 50));
        label_6->setMinimumSize(QSize(0, 50));
        label_6->setMaximumSize(QSize(16777215, 100));
        QFont font4;
        font4.setPointSize(16);
        font4.setBold(true);
        font4.setWeight(75);
        label_6->setFont(font4);
        label_6->setLayoutDirection(Qt::LeftToRight);
        label_6->setScaledContents(true);
        label_6->setAlignment(Qt::AlignCenter);
        logo = new QLabel(tab_4);
        logo->setObjectName(QStringLiteral("logo"));
        logo->setGeometry(QRect(430, 70, 421, 271));
        logo->setStyleSheet(QStringLiteral(""));
        logo->setScaledContents(true);
        label_5 = new QLabel(tab_4);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(0, 340, 1251, 50));
        label_5->setMinimumSize(QSize(0, 50));
        label_5->setMaximumSize(QSize(16777215, 100));
        label_5->setFont(font4);
        label_5->setLayoutDirection(Qt::LeftToRight);
        label_5->setScaledContents(true);
        label_5->setAlignment(Qt::AlignCenter);
        label_4 = new QLabel(tab_4);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(0, 10, 1251, 50));
        label_4->setMinimumSize(QSize(0, 50));
        label_4->setMaximumSize(QSize(16777215, 100));
        QFont font5;
        font5.setPointSize(24);
        font5.setBold(true);
        font5.setWeight(75);
        label_4->setFont(font5);
        label_4->setLayoutDirection(Qt::LeftToRight);
        label_4->setScaledContents(true);
        label_4->setAlignment(Qt::AlignCenter);
        tabWidget->addTab(tab_4, QString());
        label = new QLabel(Config);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(20, 10, 1471, 41));
        QFont font6;
        font6.setPointSize(18);
        font6.setBold(true);
        font6.setWeight(75);
        label->setFont(font6);
        label->setAlignment(Qt::AlignCenter);
        pushButton_7 = new QPushButton(Config);
        pushButton_7->setObjectName(QStringLiteral("pushButton_7"));
        pushButton_7->setGeometry(QRect(90, 620, 491, 51));
        pushButton_7->setFont(font1);
        pushButton_cerrar = new QPushButton(Config);
        pushButton_cerrar->setObjectName(QStringLiteral("pushButton_cerrar"));
        pushButton_cerrar->setGeometry(QRect(710, 620, 531, 51));
        pushButton_cerrar->setFont(font1);

        retranslateUi(Config);
        QObject::connect(pushButton_cerrar, SIGNAL(clicked()), Config, SLOT(close()));

        tabWidget->setCurrentIndex(1);
        tabWidget_2->setCurrentIndex(0);
        tabWidget_3->setCurrentIndex(2);
        tabWidget_4->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(Config);
    } // setupUi

    void retranslateUi(QWidget *Config)
    {
        Config->setWindowTitle(QApplication::translate("Config", "Form", 0));
        QTableWidgetItem *___qtablewidgetitem = tableWidget->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QApplication::translate("Config", "Proveedor", 0));
        QTableWidgetItem *___qtablewidgetitem1 = tableWidget->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QApplication::translate("Config", "Minima", 0));
        QTableWidgetItem *___qtablewidgetitem2 = tableWidget->horizontalHeaderItem(2);
        ___qtablewidgetitem2->setText(QApplication::translate("Config", "111 cft a 950 cft", 0));
        QTableWidgetItem *___qtablewidgetitem3 = tableWidget->horizontalHeaderItem(3);
        ___qtablewidgetitem3->setText(QApplication::translate("Config", "+951 cft", 0));
        QTableWidgetItem *___qtablewidgetitem4 = tableWidget->horizontalHeaderItem(4);
        ___qtablewidgetitem4->setText(QApplication::translate("Config", "2,142 a 14,500 lbs", 0));
        QTableWidgetItem *___qtablewidgetitem5 = tableWidget->horizontalHeaderItem(5);
        ___qtablewidgetitem5->setText(QApplication::translate("Config", "+ de 14,500", 0));
        QTableWidgetItem *___qtablewidgetitem6 = tableWidget_2->horizontalHeaderItem(0);
        ___qtablewidgetitem6->setText(QApplication::translate("Config", "Proveedor", 0));
        QTableWidgetItem *___qtablewidgetitem7 = tableWidget_2->horizontalHeaderItem(1);
        ___qtablewidgetitem7->setText(QApplication::translate("Config", "Contenedor 20 STD", 0));
        QTableWidgetItem *___qtablewidgetitem8 = tableWidget_2->horizontalHeaderItem(2);
        ___qtablewidgetitem8->setText(QApplication::translate("Config", "Contenedor 40 STD", 0));
        QTableWidgetItem *___qtablewidgetitem9 = tableWidget_2->horizontalHeaderItem(3);
        ___qtablewidgetitem9->setText(QApplication::translate("Config", "Contenedor 40 HC", 0));
        QTableWidgetItem *___qtablewidgetitem10 = tableWidget_2->horizontalHeaderItem(4);
        ___qtablewidgetitem10->setText(QApplication::translate("Config", "Contenedor 45 HC", 0));
        QTableWidgetItem *___qtablewidgetitem11 = tableWidget_2->horizontalHeaderItem(5);
        ___qtablewidgetitem11->setText(QApplication::translate("Config", "Contenedor 45 120", 0));
        label_2->setText(QApplication::translate("Config", "TARIFAS LCL (Less Container Load) Consolidado Maritimo ", 0));
        label_3->setText(QApplication::translate("Config", "TARIFAS FCL (Full Container Load) Conte, Completo ", 0));
        pushButton_4->setText(QApplication::translate("Config", "AGREGAR", 0));
        pushButton_6->setText(QApplication::translate("Config", "BORRAR", 0));
        pushButton_5->setText(QApplication::translate("Config", "EDITAR", 0));
        label_8->setText(QApplication::translate("Config", "MINIMO", 0));
        label_9->setText(QApplication::translate("Config", "PROVEEDOR", 0));
        groupBox->setTitle(QApplication::translate("Config", "TARIFA X CFT ", 0));
        label_14->setText(QApplication::translate("Config", "+ 951", 0));
        label_13->setText(QApplication::translate("Config", "111 cft a 950", 0));
        groupBox_2->setTitle(QApplication::translate("Config", "TARIFA X LIBRA ", 0));
        label_15->setText(QApplication::translate("Config", "2,142 a 14,500 lbs", 0));
        label_16->setText(QApplication::translate("Config", "+ de 14,500", 0));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_5), QApplication::translate("Config", "TARIFA LCL", 0));
        label_10->setText(QApplication::translate("Config", "PROVEEDOR", 0));
        label_11->setText(QApplication::translate("Config", "Contenedor 20 STD", 0));
        label_12->setText(QApplication::translate("Config", "Contenedor40 STD", 0));
        label_19->setText(QApplication::translate("Config", "Contenedor40 HC", 0));
        label_20->setText(QApplication::translate("Config", "Contenedor45 HC", 0));
        lineEdit_13->setText(QString());
        lineEdit_14->setText(QString());
        label_21->setText(QApplication::translate("Config", "Contenedor 45 120", 0));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_6), QApplication::translate("Config", "TARIFAS FCL", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("Config", "REGION", 0));
        pushButton_8->setText(QApplication::translate("Config", "BORRAR", 0));
        pushButton_agregar_aduanero->setText(QApplication::translate("Config", "AGREGAR", 0));
        pushButton_10->setText(QApplication::translate("Config", "EDITAR", 0));
        label_27->setText(QApplication::translate("Config", "GASTOS EN ORIGEN", 0));

        const bool __sortingEnabled = listWidget->isSortingEnabled();
        listWidget->setSortingEnabled(false);
        QListWidgetItem *___qlistwidgetitem = listWidget->item(0);
        ___qlistwidgetitem->setText(QApplication::translate("Config", "Seguro", 0));
        QListWidgetItem *___qlistwidgetitem1 = listWidget->item(1);
        ___qlistwidgetitem1->setText(QApplication::translate("Config", "SED", 0));
        QListWidgetItem *___qlistwidgetitem2 = listWidget->item(2);
        ___qlistwidgetitem2->setText(QApplication::translate("Config", "BI Completo", 0));
        QListWidgetItem *___qlistwidgetitem3 = listWidget->item(3);
        ___qlistwidgetitem3->setText(QApplication::translate("Config", "BI Consolidado", 0));
        QListWidgetItem *___qlistwidgetitem4 = listWidget->item(4);
        ___qlistwidgetitem4->setText(QApplication::translate("Config", "Manejo Completo", 0));
        QListWidgetItem *___qlistwidgetitem5 = listWidget->item(5);
        ___qlistwidgetitem5->setText(QApplication::translate("Config", "Manejo Consolidado", 0));
        QListWidgetItem *___qlistwidgetitem6 = listWidget->item(6);
        ___qlistwidgetitem6->setText(QApplication::translate("Config", "Carga Descarga", 0));
        listWidget->setSortingEnabled(__sortingEnabled);


        const bool __sortingEnabled1 = listWidget_4->isSortingEnabled();
        listWidget_4->setSortingEnabled(false);
        QListWidgetItem *___qlistwidgetitem7 = listWidget_4->item(0);
        ___qlistwidgetitem7->setText(QApplication::translate("Config", "Naviera", 0));
        QListWidgetItem *___qlistwidgetitem8 = listWidget_4->item(1);
        ___qlistwidgetitem8->setText(QApplication::translate("Config", "Manejo", 0));
        QListWidgetItem *___qlistwidgetitem9 = listWidget_4->item(2);
        ___qlistwidgetitem9->setText(QApplication::translate("Config", "Almacenaje", 0));
        QListWidgetItem *___qlistwidgetitem10 = listWidget_4->item(3);
        ___qlistwidgetitem10->setText(QApplication::translate("Config", "Swissport", 0));
        QListWidgetItem *___qlistwidgetitem11 = listWidget_4->item(4);
        ___qlistwidgetitem11->setText(QApplication::translate("Config", "Cargo Nav", 0));
        QListWidgetItem *___qlistwidgetitem12 = listWidget_4->item(5);
        ___qlistwidgetitem12->setText(QApplication::translate("Config", "New Inter Nav", 0));
        QListWidgetItem *___qlistwidgetitem13 = listWidget_4->item(6);
        ___qlistwidgetitem13->setText(QApplication::translate("Config", "Sobre Estadia", 0));
        QListWidgetItem *___qlistwidgetitem14 = listWidget_4->item(7);
        ___qlistwidgetitem14->setText(QApplication::translate("Config", "Rayos Gama", 0));
        QListWidgetItem *___qlistwidgetitem15 = listWidget_4->item(8);
        ___qlistwidgetitem15->setText(QApplication::translate("Config", "Gastos Portuarios", 0));
        listWidget_4->setSortingEnabled(__sortingEnabled1);


        const bool __sortingEnabled2 = listWidget_6->isSortingEnabled();
        listWidget_6->setSortingEnabled(false);
        QListWidgetItem *___qlistwidgetitem16 = listWidget_6->item(0);
        ___qlistwidgetitem16->setText(QApplication::translate("Config", "Gastos Admon.", 0));
        QListWidgetItem *___qlistwidgetitem17 = listWidget_6->item(1);
        ___qlistwidgetitem17->setText(QApplication::translate("Config", "Comision", 0));
        QListWidgetItem *___qlistwidgetitem18 = listWidget_6->item(2);
        ___qlistwidgetitem18->setText(QApplication::translate("Config", "Dvas", 0));
        QListWidgetItem *___qlistwidgetitem19 = listWidget_6->item(3);
        ___qlistwidgetitem19->setText(QApplication::translate("Config", "Duas", 0));
        QListWidgetItem *___qlistwidgetitem20 = listWidget_6->item(4);
        ___qlistwidgetitem20->setText(QApplication::translate("Config", "Almacenamiento", 0));
        QListWidgetItem *___qlistwidgetitem21 = listWidget_6->item(5);
        ___qlistwidgetitem21->setText(QApplication::translate("Config", "Multas", 0));
        QListWidgetItem *___qlistwidgetitem22 = listWidget_6->item(6);
        ___qlistwidgetitem22->setText(QApplication::translate("Config", "DAI", 0));
        QListWidgetItem *___qlistwidgetitem23 = listWidget_6->item(7);
        ___qlistwidgetitem23->setText(QApplication::translate("Config", "STD", 0));
        QListWidgetItem *___qlistwidgetitem24 = listWidget_6->item(8);
        ___qlistwidgetitem24->setText(QApplication::translate("Config", "Inspecci\303\263n", 0));
        listWidget_6->setSortingEnabled(__sortingEnabled2);

        label_54->setText(QApplication::translate("Config", "GASTOS EN DESTINO", 0));
        label_55->setText(QApplication::translate("Config", "AGENTE ADUANERO", 0));
        label_56->setText(QApplication::translate("Config", "OPC", 0));

        const bool __sortingEnabled3 = listWidget_9->isSortingEnabled();
        listWidget_9->setSortingEnabled(false);
        QListWidgetItem *___qlistwidgetitem25 = listWidget_9->item(0);
        ___qlistwidgetitem25->setText(QApplication::translate("Config", "4-7 DIAS ", 0));
        QListWidgetItem *___qlistwidgetitem26 = listWidget_9->item(1);
        ___qlistwidgetitem26->setText(QApplication::translate("Config", "8-11 DIAS ", 0));
        QListWidgetItem *___qlistwidgetitem27 = listWidget_9->item(2);
        ___qlistwidgetitem27->setText(QApplication::translate("Config", "12-EN ADELNTE", 0));
        listWidget_9->setSortingEnabled(__sortingEnabled3);

        label_68->setText(QApplication::translate("Config", "20\"", 0));
        label_69->setText(QApplication::translate("Config", "40\"", 0));
        label_17->setText(QApplication::translate("Config", "SED", 0));
        label_18->setText(QApplication::translate("Config", "SEGURO", 0));
        label_22->setText(QApplication::translate("Config", "BID COMPLETO", 0));
        label_26->setText(QApplication::translate("Config", "BID CONSOLIDADO", 0));
        label_70->setText(QApplication::translate("Config", "MANEJO COMPLETO", 0));
        label_71->setText(QApplication::translate("Config", "MANEJO CONSOLIDADO", 0));
        label_72->setText(QApplication::translate("Config", "CARGA/DESCARGA", 0));
        tabWidget_3->setTabText(tabWidget_3->indexOf(tab_7), QApplication::translate("Config", "ORIGEN", 0));
        label_23->setText(QApplication::translate("Config", "MANEJO", 0));
        label_73->setText(QApplication::translate("Config", "CARGO NAV", 0));
        label_24->setText(QApplication::translate("Config", "NAVIERA", 0));
        label_25->setText(QApplication::translate("Config", "ALMACENAJE", 0));
        label_74->setText(QApplication::translate("Config", "SWISSPORT", 0));
        label_75->setText(QApplication::translate("Config", "NEW INTER NAV", 0));
        label_76->setText(QApplication::translate("Config", "SOBRE ESTADIA", 0));
        label_77->setText(QApplication::translate("Config", "RAYOS GAMA", 0));
        label_78->setText(QApplication::translate("Config", "RAYOS GAMA", 0));
        tabWidget_3->setTabText(tabWidget_3->indexOf(tab_8), QApplication::translate("Config", "DESTINO", 0));
        label_79->setText(QApplication::translate("Config", "DVAS", 0));
        label_80->setText(QApplication::translate("Config", "GASTOS ADMON.", 0));
        label_81->setText(QApplication::translate("Config", "COMISION", 0));
        label_82->setText(QApplication::translate("Config", "DUAS", 0));
        label_83->setText(QApplication::translate("Config", "ALMACENAMIENTO", 0));
        label_84->setText(QApplication::translate("Config", "MULTAS", 0));
        label_85->setText(QApplication::translate("Config", "DAI", 0));
        label_86->setText(QApplication::translate("Config", "STD", 0));
        label_87->setText(QApplication::translate("Config", "INSPECCI\303\223N", 0));
        tabWidget_3->setTabText(tabWidget_3->indexOf(tab_19), QApplication::translate("Config", "ADUANERO", 0));
        label_88->setText(QApplication::translate("Config", "ALMACENAMIENTO", 0));
        label_89->setText(QApplication::translate("Config", "COMISION", 0));
        label_90->setText(QApplication::translate("Config", "DVAS", 0));
        label_91->setText(QApplication::translate("Config", "GASTOS ADMON.", 0));
        label_92->setText(QApplication::translate("Config", "MULTAS", 0));
        label_93->setText(QApplication::translate("Config", "DVAS", 0));
        label_94->setText(QApplication::translate("Config", "40\"", 0));
        label_95->setText(QApplication::translate("Config", "20\"", 0));
        tabWidget_3->setTabText(tabWidget_3->indexOf(tab_20), QApplication::translate("Config", "OPC", 0));
        label_28->setText(QApplication::translate("Config", "Proveedor", 0));
        comboBox_aduanero_proveedor->clear();
        comboBox_aduanero_proveedor->insertItems(0, QStringList()
         << QApplication::translate("Config", "PROVEEDOR 1", 0)
         << QApplication::translate("Config", "PROVEEDOR 2", 0)
        );
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("Config", "AGENTE ADUANERO", 0));
        label_57->setText(QApplication::translate("Config", "HONDUMARES", 0));

        const bool __sortingEnabled4 = listWidget_11->isSortingEnabled();
        listWidget_11->setSortingEnabled(false);
        QListWidgetItem *___qlistwidgetitem28 = listWidget_11->item(0);
        ___qlistwidgetitem28->setText(QApplication::translate("Config", "Gastos Admon.", 0));
        QListWidgetItem *___qlistwidgetitem29 = listWidget_11->item(1);
        ___qlistwidgetitem29->setText(QApplication::translate("Config", "Comision", 0));
        QListWidgetItem *___qlistwidgetitem30 = listWidget_11->item(2);
        ___qlistwidgetitem30->setText(QApplication::translate("Config", "Dvas", 0));
        QListWidgetItem *___qlistwidgetitem31 = listWidget_11->item(3);
        ___qlistwidgetitem31->setText(QApplication::translate("Config", "Duas", 0));
        QListWidgetItem *___qlistwidgetitem32 = listWidget_11->item(4);
        ___qlistwidgetitem32->setText(QApplication::translate("Config", "Almacenamiento", 0));
        QListWidgetItem *___qlistwidgetitem33 = listWidget_11->item(5);
        ___qlistwidgetitem33->setText(QApplication::translate("Config", "Multas", 0));
        QListWidgetItem *___qlistwidgetitem34 = listWidget_11->item(6);
        ___qlistwidgetitem34->setText(QApplication::translate("Config", "DAI", 0));
        QListWidgetItem *___qlistwidgetitem35 = listWidget_11->item(7);
        ___qlistwidgetitem35->setText(QApplication::translate("Config", "STD", 0));
        QListWidgetItem *___qlistwidgetitem36 = listWidget_11->item(8);
        ___qlistwidgetitem36->setText(QApplication::translate("Config", "Inspecci\303\263n", 0));
        listWidget_11->setSortingEnabled(__sortingEnabled4);

        pushButton_17->setText(QApplication::translate("Config", "EDITAR", 0));
        pushButton_18->setText(QApplication::translate("Config", "BORRAR", 0));
        pushButton_19->setText(QApplication::translate("Config", "AGREGAR", 0));
        label_58->setText(QApplication::translate("Config", "SELECCIONE EL PROVEEDOR", 0));
        groupBox_13->setTitle(QApplication::translate("Config", "EDITAR", 0));
        label_59->setText(QApplication::translate("Config", "MINIMO", 0));
        label_60->setText(QApplication::translate("Config", "PROVEEDOR", 0));
        groupBox_14->setTitle(QApplication::translate("Config", "TARIFA X CFT ", 0));
        label_61->setText(QApplication::translate("Config", "+ 951", 0));
        label_62->setText(QApplication::translate("Config", "111 cft a 950", 0));
        groupBox_15->setTitle(QApplication::translate("Config", "TARIFA X LIBRA ", 0));
        label_63->setText(QApplication::translate("Config", "2,142 a 14,500 lbs", 0));
        label_64->setText(QApplication::translate("Config", "+ de 14,500", 0));
        tabWidget_4->setTabText(tabWidget_4->indexOf(tab_17), QApplication::translate("Config", "TARIFA LCL", 0));
        label_65->setText(QApplication::translate("Config", "NOMBRE", 0));
        label_66->setText(QApplication::translate("Config", "VALOR", 0));
        label_67->setText(QApplication::translate("Config", "DESCRIPCION", 0));
        tabWidget_4->setTabText(tabWidget_4->indexOf(tab_18), QApplication::translate("Config", "TARIFAS FCL", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QApplication::translate("Config", "BODEGA FISCAL", 0));
        label_6->setText(QApplication::translate("Config", "TEL:+504  96276956            CORREO:  xibertec@outlook.com                     VERSI\303\223N: 1.0", 0));
        logo->setText(QString());
        label_5->setText(QApplication::translate("Config", "PARA MAS INFORMACI\303\223N", 0));
        label_4->setText(QApplication::translate("Config", "DISE\303\221O Y PROGRAMACI\303\223N HECHA POR", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_4), QApplication::translate("Config", "MAS INFORMACI\303\223N", 0));
        label->setText(QApplication::translate("Config", "IMPORTACIONES TECSYS", 0));
        pushButton_7->setText(QApplication::translate("Config", "GUARDAR", 0));
        pushButton_cerrar->setText(QApplication::translate("Config", "SALIR", 0));
    } // retranslateUi

};

namespace Ui {
    class Config: public Ui_Config {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_CONFIG_H
